{{- if .Values.localDev.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.localSecrets }}
  labels:
    {{- include "tvevents.labels" . | nindent 4 }}
  annotations:
    {{- include "tvevents.annotations" . | nindent 4 }}
type: Opaque
data:
  RDS_HOST: {{ required "RDS_HOST is required!" .Values.localDev.RDS_HOST | b64enc }}
  RDS_DB: {{ required "RDS_DB is required!" .Values.localDev.RDS_DB | b64enc }}
  RDS_USER: {{ required "RDS_USER is required!" .Values.localDev.RDS_USER | b64enc }}
  RDS_PASS: {{ required "RDS_PASS is required!" .Values.localDev.RDS_PASS | b64enc }}
  RDS_PORT: {{ required "RDS_PORT is required!" (printf "%d" .Values.localDev.RDS_PORT) | b64enc }}
  T1_SALT: {{ required "T1_SALT is required!" .Values.localDev.T1_SALT | b64enc }}
  AWS_ACCESS_KEY_ID: {{ required "AWS_ACCESS_KEY_ID is required!" .Values.localDev.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "AWS_SECRET_ACCESS_KEY is required!" .Values.localDev.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_SESSION_TOKEN: {{ required "AWS_SESSION_TOKEN is required!" .Values.localDev.AWS_SESSION_TOKEN | b64enc }}
  LOCAL_OTEL_EXPORTER_OTLP_HEADERS: {{ required "LOCAL_OTEL_EXPORTER_OTLP_HEADERS is required!" .Values.localDev.LOCAL_OTEL_EXPORTER_OTLP_HEADERS | b64enc }}
{{- end }}
