{{- if not .Values.localDev.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store  # This name must match the secretStoreRef.name in your ExternalSecret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "tvevents.labels" . | nindent 4 }}
  annotations:
    {{ include "tvevents.annotations" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.cloud_region }}
{{- end }}
