apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    konghq.com/upstream-policy: {{ .Release.Name }}
    {{- include "tvevents.annotations" . | nindent 4 }}
  labels:
    {{- include "tvevents.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    {{- if .Values.labels }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
