receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.name
        value: tvevents-k8s
        action: upsert
      - key: deployment.environment
        from_attribute: ENV
        action: upsert

exporters:
  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: ${NEW_RELIC_API_KEY}

  logging:
    loglevel: warn

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/newrelic, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/newrelic, logging]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/newrelic, logging]
