[pytest]
addopts = --cov-report xml:coverage.xml --cov-report=html:coverage_report --cov-report term --cov=app --cov-fail-under=80 -v -p no:cacheprovider
norecursedirs = cntools_py3 cnlib
asyncio_mode = auto
env =
    OTEL_SDK_DISABLED=true
filterwarnings =
    ignore::DeprecationWarning
