# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py35,py36,py27
[testenv]
deps=
    pytest
    moto
commands=py.test {posargs: cnlib/tests/test_s3.py cnlib/tests/test_firehose.py cnlib/tests/test_redshift.py  cnlib/tests/test_sqs.py}

# run single test file with: tox -- cnlib/tests/test_sqs.py
