{{- if not .Values.localDev.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-application-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "tvevents.labels" . | nindent 4 }}
  annotations:
    {{ include "tvevents.annotations" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}-secret-store
  target:
    name: {{ .Release.Name }}-application-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.environment }}/{{ .Values.keyDomain }}
{{- end }}
