[pytest]
addopts = --cov-report xml:coverage.xml  --cov-report=html:coverage_report --cov-report term --cov=app --cov-fail-under=90 -v -p no:cacheprovider
norecursedirs = cntools_py3 cnlib
env =
    T1_SALT=stupidquestionhowtotithelotswife
    FLASK_ENV=local-testing
    SEND_EVERGREEN=True
    EVERGREEN_FIREHOSE_NAME=EVERGREEN_FIREHOSE_NAME
    DEBUG_EVERGREEN_FIREHOSE_NAME=DEBUG_EVERGREEN_FIREHOSE_NAME
    SEND_LEGACY=True
    LEGACY_FIREHOSE_NAME=LEGACY_FIREHOSE_NAME
    DEBUG_LEGACY_FIREHOSE_NAME=DEBUG_LEGACY_FIREHOSE_NAME
    BLACKLIST_CHANNEL_IDS_CACHE_FILEPATH=/tmp/.blacklisted_channel_ids_cache
    OTEL_SDK_DISABLED=true
    LOG_LEVEL=DEBUG