#! /usr/bin/env python

import protobuf

# from dts-py; generated by cn-protobuf, dts-py
# TODO: generic PB type
from prototcp.protos import PBUmpEmit_pb2
from prototcp import types as proto_types


__author__ = "James Bartolome <james.bartolome@inscape.tv>"


def read_next_message(blob):

    for msg in protobuf.get_next_message(blob):
        record = PBUmpEmit_pb2.Record()
        record.ParseFromString(msg)
        yield record

