#! /usr/bin/env python

import logging
import struct
# from dts-py; generated by cn-protobuf, dts-py
# TODO: generic PB type
# from prototcp.protos import PBUmpEmit_pb2
from prototcp import types as proto_types


__author__ = "James Bartolome <james.bartolome@inscape.tv>"


class DeserializeException(Exception):
    pass


def make_header(protobuf_record):
    """
    Reads protobuf message type, calculates length, and generates header

    :param google.protobuf.reflection.GeneratedProtocolMessageType record

    :return string msg_header: header
    """
    # cf. https://cognet.atlassian.net/wiki/display/ENG/Protobuf+at+Cognitive+Networks
    msg_lead = ";"
    msg_type = struct.pack('B', proto_types.pbumpemit_t)
    msg_len = struct.pack('>I', len(protobuf_record))

    msg_header = msg_lead + msg_type + msg_len
    return msg_header


def make_message(record, test=False):
    """
    :param google.protobuf.reflection.GeneratedProtocolMessageType record
    :param bool test: Attempts to deserialize from serialized record
        for validation

    :return string message: Serialized representation of protobuf record
        prepended with header
    """

    s = record.SerializeToString()

    if test:
        try:
            record.ParseFromString(s)
        except:
            logging.error("Deserializing error. Original string: {}".format(repr(s)))
            return

    message = make_header(s) + s
    return message


def get_next_message(blob):
    """
    Generator to get next chunk of serialized data in message stream (blob)

    :param string blob: binary string of data:
        (<lead char><pb type><data length><data>)+

    :return string data: serialized data, which becomes 
        google.protobuf.reflection.GeneratedProtocolMessageType when deserialized
    """

    # in bytes
    HEADER_LEAD_FIELD_LENGTH = 1
    HEADER_TYPE_FIELD_LENGTH = 1
    HEADER_LENGTH_FIELD_LENGTH = 4

    i = 0
    while True:

        try:
            header_lead = blob[i]
        except IndexError:
            # no more messages to read from blob
            return
            
        if not header_lead == ";":
            raise DeserializeException("blob tail does not start with delimiter: {}".format(
                repr(blob[i:])))
        
        msg_type = struct.unpack("B", blob[i + 1])[0]
        if not msg_type == proto_types.pbumpemit_t:
            raise DeserializeException("message is of unexpected type, "
                "expected=({}) actual=({}): {}".format(
                repr(proto_types.pbumpemit_t), repr(msg_type), repr(blob[i:])))

        msg_len = struct.unpack(">I", blob[i + 2:i + 6])[0]
        msg_end = i + 6 + msg_len
        data = blob[i + 6:i + 6 + msg_len]

        yield data

        i = msg_end

